import "./globals.css";
import Header from "../components/Header";
import Contact from "@/components/Contact";
import Testimonials from "@/components/Testimonials";
import Services from "@/services/slug/Services";
import Teams from "@/components/Teams";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Tani Warga",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Services />
        <Testimonials />
        <Teams />
        <Contact />
        <Footer />
      </body>
    </html>
  );
}
